import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/db/raw';
import type {Person,Plan,GoalType,Submission} from '@/lib/manager';
type TimedTask={id:string;member_id:string;category:string;quantity:number;status:string;started_at:string|null;elapsed_seconds:number;submitted_at:string|null;delete_requested_at:string|null;delete_reason:string;version:number};
export const dynamic='force-dynamic';
class Problem extends Error{constructor(message:string,public status=400){super(message)}}
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
function text(v:unknown,max=160){if(typeof v!=='string'||!v.trim()||v.length>max)throw new Problem('Complete all required fields.');return v.trim()}
function driveLink(value:unknown){if(value===undefined||value==='')return '';if(typeof value!=='string'||value.length>2000)throw new Problem('Enter a valid Google Drive link.');if(!value.trim())return '';try{const url=new URL(value.trim());if(url.protocol==='https:'&&['drive.google.com','docs.google.com'].includes(url.hostname)&&!url.username&&!url.password&&!url.port)return url.href}catch{}throw new Problem('Use an HTTPS Google Drive or Google Docs link.');}
function quantity(v:unknown,unit:string){if(typeof v!=='number'||!Number.isFinite(v)||v<=0||v>100000||(unit==='jobs'&&!Number.isInteger(v)))throw new Problem('Enter a positive quantity; jobs must be whole numbers.');return v}
async function context(){const user=await getChatGPTUser();if(!user)throw new Problem('Sign in to your workspace.',401);const db=database();await db.prepare('INSERT OR IGNORE INTO workspace(id,owner_id) VALUES(1,?)').bind(user.userId).run();const owner=await db.prepare('SELECT owner_id FROM workspace WHERE id=1').first<{owner_id:string}>();if(owner?.owner_id===user.userId)await db.prepare('INSERT OR IGNORE INTO people(id,user_id,email,name,role,job) VALUES(?,?,?,?,?,?)').bind(user.userId,user.userId,user.email.toLowerCase(),user.fullName||'Workspace manager','admin','Workspace manager').run();await db.prepare('UPDATE people SET user_id=? WHERE email=? AND user_id IS NULL AND active=1').bind(user.userId,user.email.toLowerCase()).run();const me=await db.prepare('SELECT * FROM people WHERE user_id=? AND active=1').bind(user.userId).first<Person>();if(!me)throw new Problem('Ask your team lead to add your sign-in email.',403);return {db,me}}
async function snapshot(){const {db,me}=await context();const clause=me.role==='admin'?'1=1':me.role==='manager'?'(id=? OR manager_id=?)':'id=?';const args=me.role==='admin'?[]:me.role==='manager'?[me.id,me.id]:[me.id];const people=(await db.prepare(`SELECT * FROM people WHERE ${clause} ORDER BY name`).bind(...args).all<Person>()).results;const ids=people.filter(p=>['creator','manager'].includes(p.role)).map(p=>p.id);const placeholders=ids.map(()=>'?').join(',')||'NULL';const plans=(await db.prepare(`SELECT * FROM plans WHERE member_id IN (${placeholders}) ORDER BY month DESC`).bind(...ids).all<Plan>()).results;const types=(await db.prepare(me.role==='admin'?'SELECT * FROM goal_types ORDER BY name':`SELECT * FROM goal_types WHERE manager_id='workspace' OR manager_id=? OR id IN (SELECT type_id FROM plans WHERE member_id IN (${placeholders})) ORDER BY name`).bind(...(me.role==='admin'?[]:[me.role==='manager'?me.id:me.manager_id,...ids])).all<GoalType>()).results;const submissions=(await db.prepare(`SELECT s.id,s.plan_id,s.daily_task_id,s.title,s.url,s.completed,s.quantity,s.status,s.feedback,s.version,COALESCE(d.actual_hours,0) AS actual_hours FROM submissions s JOIN plans p ON p.id=s.plan_id LEFT JOIN daily_tasks d ON d.id=s.daily_task_id WHERE p.member_id IN (${placeholders}) ORDER BY s.completed DESC`).bind(...ids).all<Submission>()).results;return {me,people,types,plans,submissions}}
function fail(e:unknown){if(e instanceof Problem)return json({error:e.message},e.status);console.error(e);return json({error:'Unable to save or load. Please retry.'},503)}
export async function GET(){try{return json(await snapshot())}catch(e){return fail(e)}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)throw new Problem('Origin not allowed.',403);const raw=await req.text();if(raw.length>250000)throw new Problem('Request too large.');const b=JSON.parse(raw);const {db,me}=await context();const id=crypto.randomUUID();
async function member(id:unknown,allowSelf=false){const p=await db.prepare('SELECT * FROM people WHERE id=?').bind(text(id)).first<Person>();if(!p||!['creator','manager'].includes(p.role)||(me.role==='manager'&&p.manager_id!==me.id&&!(allowSelf&&p.id===me.id))||(me.role==='creator'&&p.id!==me.id))throw new Problem('Employee unavailable.',403);return p}
async function manageablePerson(id:unknown){if(me.role!=='admin')return member(id);const p=await db.prepare('SELECT * FROM people WHERE id=?').bind(text(id)).first<Person>();if(!p||!['manager','creator'].includes(p.role))throw new Problem('Person unavailable.',403);return p}
function manager(){if(!['manager','admin'].includes(me.role))throw new Problem('Only the assigned team lead can do this.',403)}
if(b.action==='person'){if(!['manager','admin'].includes(me.role))throw new Problem('Not permitted.',403);const name=text(b.name,100),email=text(b.email,254).toLowerCase(),job=text(b.job,100),employeeId=typeof b.employee_id==='string'?b.employee_id.trim().slice(0,30):'';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Problem('Enter a valid email.');if(b.id){const p=await manageablePerson(b.id);if(p.email!==email)throw new Problem('Sign-in email cannot be changed; add a new employee instead.');await db.prepare('UPDATE people SET name=?,job=?,employee_id=? WHERE id=?').bind(name,job,employeeId||null,p.id).run()}else{const role=me.role==='admin'&&b.role==='manager'?'manager':'creator';const managerId=me.role==='manager'?me.id:role==='manager'?null:text(b.manager_id);if(managerId&&!await db.prepare("SELECT id FROM people WHERE id=? AND role='manager' AND active=1").bind(managerId).first())throw new Problem('Choose an active team lead.');if(await db.prepare('SELECT id FROM people WHERE email=?').bind(email).first())throw new Problem('This email already belongs to a workspace employee.');const createPerson=db.prepare('INSERT INTO people(id,email,name,role,job,manager_id,employee_id) VALUES(?,?,?,?,?,?,?)').bind(id,email,name,role,job,managerId,employeeId||null);if(role==='manager'){const createOthers=db.prepare('INSERT INTO goal_types(id,manager_id,name,unit) VALUES(?,?,?,?)').bind(`others_${id}`,id,'Others','jobs');const results=await db.batch([createPerson,createOthers]);if(results.some(result=>!result.meta.changes))throw new Problem('Could not create the team lead.',409)}else await createPerson.run()}}
else if(b.action==='active'){if(!['manager','admin'].includes(me.role))throw new Problem('Not permitted.',403);const p=await manageablePerson(b.id);if(p.role==='manager'&&p.active&&await db.prepare('SELECT id FROM people WHERE manager_id=? AND active=1').bind(p.id).first())throw new Problem('Transfer or deactivate active team employees before deactivating their team lead.');await db.prepare('UPDATE people SET active=? WHERE id=?').bind(p.active?0:1,p.id).run()}
else if(b.action==='transfer'){if(me.role!=='admin')throw new Problem('Only admins can transfer employees.',403);const p=await member(b.id);const managerId=text(b.manager_id);if(!await db.prepare("SELECT id FROM people WHERE id=? AND role='manager' AND active=1").bind(managerId).first())throw new Problem('Choose an active team lead.');await db.prepare('UPDATE people SET manager_id=? WHERE id=?').bind(managerId,p.id).run()}
else if(b.action==='type'){manager();const existingType=b.id?await db.prepare('SELECT * FROM goal_types WHERE id=?').bind(text(b.id)).first<GoalType>():null;const ownerId=me.role==='admin'?(existingType?.manager_id||'workspace'):me.id;if(ownerId!=='workspace'&&!await db.prepare("SELECT id FROM people WHERE id=? AND role='manager' AND active=1").bind(ownerId).first())throw new Problem('Choose an active team lead.');const name=text(b.name,60);if(!['jobs','hours'].includes(b.unit))throw new Problem('Choose jobs or hours.');if(await db.prepare('SELECT id FROM goal_types WHERE manager_id=? AND lower(name)=lower(?) AND id!=?').bind(ownerId,name,b.id||'').first())throw new Problem('This goal type already exists.');if(b.id){const old=await db.prepare('SELECT * FROM goal_types WHERE id=? AND manager_id=?').bind(text(b.id),ownerId).first<GoalType>();if(!old)throw new Problem('Type unavailable.',403);if(old.unit!==b.unit&&await db.prepare('SELECT id FROM plans WHERE type_id=?').bind(old.id).first())throw new Problem('A type used in goals cannot change units.');await db.prepare('UPDATE goal_types SET name=?,unit=? WHERE id=?').bind(name,b.unit,old.id).run()}else await db.prepare('INSERT INTO goal_types VALUES(?,?,?,?)').bind(id,ownerId,name,b.unit).run()}
else if(b.action==='plan'){manager();const p=await member(b.member_id,true);if(!p.active)throw new Problem('Reactivate this employee before assigning goals.');const month=text(b.month,7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw new Problem('Choose a valid month.');const type=await db.prepare("SELECT * FROM goal_types WHERE id=? AND (manager_id=? OR manager_id='workspace')").bind(text(b.type_id),me.role==='admin'?(p.role==='manager'?p.id:p.manager_id):me.id).first<GoalType>();if(!type)throw new Problem('Choose one of your goal types.');const target=type.name.toLowerCase()==='others'&&Number(b.target)===0?0:quantity(b.target,type.unit),rate=type.unit==='hours'?1:Number(b.hours_per_job);if(type.unit==='jobs'&&type.name.toLowerCase()!=='others'&&(!Number.isFinite(rate)||rate<=0||rate>1000))throw new Problem('Enter valid hours per job.');await db.prepare('INSERT INTO plans(id,member_id,type_id,month,target,hours_per_job) VALUES(?,?,?,?,?,?) ON CONFLICT(member_id,month,type_id) DO UPDATE SET target=excluded.target,hours_per_job=excluded.hours_per_job').bind(id,p.id,type.id,month,target,type.name.toLowerCase()==='others'?null:rate).run()}
else if(b.action==='historical-import'){
 if(!['creator','manager'].includes(me.role))throw new Problem('Only employees can import their own historical work.',403);
 if(!Array.isArray(b.entries)||!b.entries.length||b.entries.length>100)throw new Problem('Add between 1 and 100 historical entries.');
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}),lastDay=today<'2026-09-30'?today:'2026-09-30',stamp=new Date().toISOString(),seen=new Set<string>(),writes=[];
 for(const rawEntry of b.entries){
  if(!rawEntry||typeof rawEntry!=='object')throw new Problem('Check every historical entry.');
  const entry=rawEntry as Record<string,unknown>,completed=text(entry.completed,10),title=text(entry.title,160),url=driveLink(entry.url),planId=text(entry.plan_id);
  if(!/^2026-09-([0-2]\d|30)$/.test(completed)||completed<'2026-09-15'||completed>lastDay)throw new Problem(`Historical dates must be from 15 September 2026 through ${lastDay}.`);
  const plan=await db.prepare('SELECT * FROM plans WHERE id=? AND member_id=? AND month=?').bind(planId,me.id,'2026-09').first<Plan>();if(!plan)throw new Problem('Choose one of your assigned September goals.');
  const type=await db.prepare('SELECT * FROM goal_types WHERE id=?').bind(plan.type_id).first<GoalType>();if(!type)throw new Problem('Goal type unavailable.');
  const amount=quantity(Number(entry.quantity),type.unit),actual=Number(entry.actual_hours);if(!Number.isFinite(actual)||actual<0||actual>1000)throw new Problem('Actual hours must be between 0 and 1000.');
  const key=[completed,title.toLowerCase(),type.name.toLowerCase(),url].join('|');if(seen.has(key))throw new Problem(`Duplicate entry: ${title}.`);seen.add(key);
  if(await db.prepare('SELECT d.id FROM daily_tasks d LEFT JOIN submissions s ON s.daily_task_id=d.id WHERE d.member_id=? AND d.work_date=? AND lower(d.title)=lower(?) AND lower(d.category)=lower(?) AND COALESCE(s.url,\'\')=?').bind(me.id,completed,title,type.name,url).first())throw new Problem(`This work already exists: ${title}.`);
  const taskId=crypto.randomUUID(),submissionId=crypto.randomUUID(),rate=plan.hours_per_job,estimated=rate===null?actual:Math.round(amount*rate*100)/100,seconds=Math.round(actual*3600);
  writes.push(db.prepare("INSERT INTO daily_tasks(id,member_id,work_date,title,category,quantity,due_date,priority,status,estimated_hours,actual_hours,notes,started_at,elapsed_seconds,submitted_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)").bind(taskId,me.id,completed,title,type.name,amount,completed,'normal','done',estimated,actual,'Historical work entry',null,seconds,stamp));
  writes.push(db.prepare("INSERT INTO submissions(id,plan_id,daily_task_id,title,url,completed,quantity,status,feedback,version) VALUES(?,?,?,?,?,?,?,'review','',1)").bind(submissionId,plan.id,taskId,title,url,completed,amount));
 }
 const results=await db.batch(writes);if(results.some(result=>!result.meta.changes))throw new Problem('Could not save every historical entry.',409);
}
else if(b.action==='submit'){
 if(!['creator','manager'].includes(me.role))throw new Problem('Only employees submit their own work.',403);
 const plan=await db.prepare('SELECT * FROM plans WHERE id=? AND member_id=?').bind(text(b.plan_id),me.id).first<Plan>();if(!plan)throw new Problem('Goal unavailable.',403);
 const type=await db.prepare('SELECT * FROM goal_types WHERE id=?').bind(plan.type_id).first<GoalType>();
 const amount=quantity(b.quantity,type!.unit),title=text(b.title),url=driveLink(b.url),completed=text(b.completed,10);
 if(!/^\d{4}-\d{2}-\d{2}$/.test(completed)||!Number.isFinite(Date.parse(completed))||new Date(completed).toISOString().slice(0,10)!==completed||completed>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}))throw new Problem('Enter a valid completion date, no later than today.');
 const existing=b.id?await db.prepare('SELECT * FROM submissions WHERE id=? AND plan_id=?').bind(text(b.id),plan.id).first<Submission>():null;
 if(b.id&&(!existing||!['review','changes'].includes(existing.status)||existing.version!==b.version))throw new Problem('Submission changed. Refresh and try again.',409);
 if(existing?.status==='review'){
  const result=await db.prepare("UPDATE submissions SET title=?,url=?,completed=?,quantity=?,version=version+1 WHERE id=? AND plan_id=? AND status='review' AND version=?").bind(title,url,completed,amount,existing.id,plan.id,existing.version).run();
  if(!result.meta.changes)throw new Problem('Submission changed. Refresh and try again.',409);
  return json(await snapshot());
 }
 const taskId=existing?.daily_task_id||text(b.daily_task_id);
 const task=await db.prepare('SELECT * FROM daily_tasks WHERE id=? AND member_id=?').bind(taskId,me.id).first<TimedTask>();
 if(!task||task.category!==type?.name||task.status!=='ready'||task.elapsed_seconds<=0||task.submitted_at)throw new Problem('Mark a daily task complete in the same goal type before submitting.',400);
 if(await db.prepare('SELECT id FROM submissions WHERE daily_task_id=? AND id!=?').bind(task.id,existing?.id||'').first())throw new Problem('This daily task already has a submission.',409);
 const now=Date.now(),stamp=new Date(now).toISOString(),seconds=task.elapsed_seconds+(task.started_at?Math.max(0,Math.floor((now-Date.parse(task.started_at))/1000)):0),actual=Math.round(seconds/36)/100;
 const submissionWrite=existing
 ?db.prepare("UPDATE submissions SET title=?,url=?,completed=?,quantity=?,status='review',feedback='',version=version+1 WHERE id=? AND plan_id=? AND status='changes' AND version=?").bind(title,url,completed,amount,existing.id,plan.id,existing.version)
 :db.prepare("INSERT INTO submissions(id,plan_id,daily_task_id,title,url,completed,quantity) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM daily_tasks WHERE id=? AND member_id=? AND version=? AND submitted_at IS NULL)").bind(id,plan.id,task.id,title,url,completed,amount,task.id,me.id,task.version);
 const taskWrite=db.prepare("UPDATE daily_tasks SET status='done',started_at=NULL,elapsed_seconds=?,actual_hours=?,submitted_at=?,version=version+1 WHERE id=? AND member_id=? AND version=? AND submitted_at IS NULL").bind(seconds,actual,stamp,task.id,me.id,task.version);
 const result=await db.batch([submissionWrite,taskWrite]);if(result.some(r=>!r.meta.changes))throw new Problem('Task or submission changed. Refresh and try again.',409);
}
else if(b.action==='review'){manager();const s=await db.prepare('SELECT s.*,p.member_id FROM submissions s JOIN plans p ON p.id=s.plan_id WHERE s.id=?').bind(text(b.id)).first<Submission&{member_id:string}>();if(!s)throw new Problem('Submission unavailable.',404);await member(s.member_id);if(!['approved','changes'].includes(b.status))throw new Problem('Choose a review decision.');const feedback=b.status==='changes'?text(b.feedback,2000):'';const reviewWrite=db.prepare("UPDATE submissions SET status=?,feedback=?,version=version+1 WHERE id=? AND status='review' AND version=?").bind(b.status,feedback,s.id,b.version);if(b.status==='changes'&&s.daily_task_id){const reopen=db.prepare("UPDATE daily_tasks SET status='hold',submitted_at=NULL,version=version+1 WHERE id=? AND member_id=? AND status='done'").bind(s.daily_task_id,s.member_id);const results=await db.batch([reviewWrite,reopen]);if(results.some(r=>!r.meta.changes))throw new Problem('Submission changed. Refresh before reviewing.',409)}else{const result=await reviewWrite.run();if(!result.meta.changes)throw new Problem('Submission changed. Refresh before reviewing.',409)}}
else if(b.action==='approve-task-delete'){manager();const task=await db.prepare('SELECT * FROM daily_tasks WHERE id=?').bind(text(b.id)).first<TimedTask>();if(!task)throw new Problem('Task unavailable.',404);await member(task.member_id);if(!task.delete_requested_at)throw new Problem('This task has no deletion request.');if(task.submitted_at)throw new Problem('Submitted tasks cannot be deleted.');const result=await db.prepare('DELETE FROM daily_tasks WHERE id=? AND member_id=? AND version=? AND delete_requested_at IS NOT NULL').bind(task.id,task.member_id,b.version).run();if(!result.meta.changes)throw new Problem('Task changed. Refresh and try again.',409)}
else throw new Problem('Unknown action.');return json(await snapshot())}catch(e){if(e instanceof SyntaxError||e instanceof TypeError)return json({error:'Check the submitted fields.'},400);return fail(e)}}
