'use client';
import {Users,Target,Clock3,CheckCheck,ArrowUpRight} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {credit,type ManagerState,type Person,type Plan,type Submission} from '@/lib/manager';
export default function AdminDashboard({data,people,plans,submissions,scope,onTeam,onManagers,onGoals}:{scope:string;data:ManagerState;people:Person[];plans:Plan[];submissions:Submission[];onTeam:(id:string)=>void;onManagers:()=>void;onGoals:()=>void}){
 const managers=data.people.filter(p=>p.role==='manager'&&(scope==='all'||p.id===scope));
 const jobs=plans.filter(p=>data.types.find(t=>t.id===p.type_id)?.unit==='jobs');
 const hours=plans.filter(p=>data.types.find(t=>t.id===p.type_id)?.unit==='hours');
 const target=jobs.reduce((n,p)=>n+p.target,0),done=jobs.reduce((n,p)=>n+credit(p.id,submissions),0);
 const missing=people.filter(p=>p.active&&!plans.some(g=>g.member_id===p.id));
 return <div className="admin-dashboard"><section className="admin-intro"><div><div className="eyebrow">Workspace overview</div><h2>A clear view of every team.</h2><p className="subtext">Keep people connected and monthly goals in sight.</p></div><button className="secondary" onClick={onManagers}>Manage team leads <ArrowUpRight size={16}/></button></section><div className="stats">{[{name:'Active employees',value:people.filter(p=>p.active).length,note:'Within selected team scope',icon:Users},{name:'Jobs delivered',value:`${done} / ${target}`,note:'Submitted and approved',icon:Target},{name:'Awaiting review',value:submissions.filter(s=>s.status==='review').length,note:'For assigned team leads',icon:Clock3},{name:'Hours logged',value:Math.round(hours.reduce((n,p)=>n+credit(p.id,submissions),0)*100)/100,note:`${hours.reduce((n,p)=>n+p.target,0)} hours planned`,icon:CheckCheck}].map(s=><article className="stat" key={s.name}><div className="stat-label"><s.icon size={16}/>{s.name}</div><div className="stat-value">{s.value}</div><p className="stat-note">{s.note}</p></article>)}</div><section className="work-surface"><div className="toolbar"><div><h2 className="manager-heading">Teams at a glance</h2><p className="hint">Monthly progress by team lead</p></div><span className="pill">{managers.filter(m=>m.active).length}  active team leads</span></div><div className="admin-team-grid">{managers.map(m=>{const team=people.filter(p=>p.manager_id===m.id),goals=jobs.filter(p=>team.some(t=>t.id===p.member_id)),t=goals.reduce((n,p)=>n+p.target,0),d=goals.reduce((n,p)=>n+credit(p.id,submissions),0);return <article className="admin-team-card" key={m.id}><div className="row spread"><span className="avatar">{m.name.slice(0,2).toUpperCase()}</span><span className="pill">{m.active?'Active':'Inactive'}</span></div><h3>{m.name}</h3><p className="hint">{team.filter(p=>p.active).length}  active employees in scope</p><div className="row spread"><strong>{d} / {t} jobs</strong><span className="hint">{t?Math.round(d/t*100)+'%':'No job targets'}</span></div><Progress value={t?Math.min(100,d/t*100):0} aria-label={`${m.name}: ${d} of ${t} jobs`}/><button className="quiet" onClick={()=>onTeam(m.id)}>Manage team <ArrowUpRight size={14}/></button></article>})}</div>{!managers.length&&<p className="manager-empty">Add a team lead, then assign team employees to them.</p>}</section><section className="work-surface admin-attention"><div><h2 className="manager-heading">Monthly planning</h2><p className="subtext">{missing.length?`${missing.length} active members have no goals for this month.`:'Every active employee in scope has monthly goals.'}</p>{missing.length>0&&<p className="hint">{missing.map(p=>p.name).join(', ')}</p>}</div><button className="secondary" onClick={onGoals}>View monthly goals <ArrowUpRight size={16}/></button></section></div>
}
