'use client';
import {useState} from 'react';
import {ChevronLeft,ChevronRight,ArrowLeft,Target,CheckCheck,Clock3,Users} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Empty} from '@/components/ui/empty';
import {localDate,kinds,roles,type State,type Task} from '@/lib/model';
import PersonalDashboard from './personal-dashboard';

export default function ManagerDashboard({data,month,setMonth,onSaved,onTask,onTeam}:{data:State;month:string;setMonth:(m:string)=>void;onSaved:(s:State)=>void;onTask:(t:Task)=>void;onTeam:()=>void}){
 const [person,setPerson]=useState<string|null>(null);
 const manager=data.me.role==='manager';
 const goals=data.personalGoals.filter(g=>g.month===month);
 const members=data.members.filter(m=>m.role==='creator'||m.role==='manager'||goals.some(g=>g.member_id===m.id));
 const done=data.tasks.filter(t=>t.completed.startsWith(month)&&['review','approved','scheduled'].includes(t.status));
 const reviews=data.tasks.filter(t=>t.status==='review'&&t.completed.startsWith(month)).sort((a,b)=>a.completed.localeCompare(b.completed));
 const overdue=data.tasks.filter(t=>t.due.startsWith(month)&&t.due<localDate()&&['planned','progress','changes'].includes(t.status)).sort((a,b)=>a.due.localeCompare(b.due));
 const target=goals.filter(g=>g.kind!=='ai_hours').reduce((n,g)=>n+g.quantity,0);
 const completed=done.filter(t=>t.kind!=='ai_hours'&&goals.some(g=>g.member_id===t.assignee&&g.kind===t.kind)).length;
 const assigned=members.filter(m=>goals.some(g=>g.member_id===m.id)).length;
 const date=new Date(month+'-01T12:00:00'),label=date.toLocaleDateString('en-IN',{month:'long',year:'numeric'});
 function move(n:number){setMonth(localDate(new Date(date.getFullYear(),date.getMonth()+n,1)).slice(0,7))}
 if(person)return <><button className="quiet" style={{marginBottom:18}} onClick={()=>setPerson(null)}><ArrowLeft size={16}/>Back to team overview</button><PersonalDashboard key={person} initialMemberId={person} data={data} month={month} setMonth={setMonth} onSaved={onSaved}/></>;
 function queue(items:Task[],empty:string){return items.length?<div className="manager-queue">{items.map(t=><button key={t.id} onClick={()=>onTask(t)}><strong>{t.title}</strong><span>{data.members.find(m=>m.id===t.assignee)?.name} · {data.channels.find(c=>c.id===t.channel_id)?.name}</span><small>{kinds[t.kind]} · {t.status==='review'?'Completed '+t.completed:'Due '+t.due}</small></button>)}</div>:<p className="manager-empty">{empty}</p>}
 return <div className="manager-dashboard"><div className="toolbar personal-toolbar"><div className="row"><button className="quiet" aria-label="Previous manager month" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><span className="month">{label}</span><button className="quiet" aria-label="Next manager month" onClick={()=>move(1)}><ChevronRight size={18}/></button><button className="secondary" onClick={()=>setMonth(localDate().slice(0,7))}>This month</button></div><span className="hint">{manager?'Plan the month. Keep the team moving.':'Admin overview · Managers assign monthly goals'}</span></div>
 <div className="stats">{[{icon:Users,label:'People with goals',value:`${assigned} / ${members.length}`,note:'Creators and managers with a plan'},{icon:Target,label:'Monthly job goal',value:target,note:'Across personal goal plans'},{icon:CheckCheck,label:'Completed against goals',value:completed,note:'Includes submissions awaiting review'},{icon:Clock3,label:'Awaiting review',value:reviews.length,note:'Completed in the selected month'}].map(s=><div className="stat" key={s.label}><div className="stat-label"><s.icon size={16}/>{s.label}</div><div className="stat-value">{s.value}</div><div className="stat-note">{s.note}</div></div>)}</div>
 <section className="work-surface"><div className="toolbar"><div><h2 className="manager-heading">Team monthly goals</h2><p className="hint">Assign a plan to each person, then track their delivery across channels.</p></div><span className="pill">{members.length-assigned} without goals</span></div>{members.length?<Table><TableHeader><TableRow><TableHead>Team member</TableHead><TableHead>Completed / goal</TableHead><TableHead>Progress</TableHead><TableHead>AI hours</TableHead><TableHead>Monthly plan</TableHead></TableRow></TableHeader><TableBody>{members.map(m=>{const plan=goals.filter(g=>g.member_id===m.id),jobs=plan.filter(g=>g.kind!=='ai_hours'),total=jobs.reduce((n,g)=>n+g.quantity,0),count=done.filter(t=>t.assignee===m.id&&jobs.some(g=>g.kind===t.kind)).length,ai=plan.find(g=>g.kind==='ai_hours'),hours=done.filter(t=>t.assignee===m.id&&t.kind==='ai_hours').reduce((n,t)=>n+t.completed_hours,0),pct=total?Math.round(count/total*100):0;return <TableRow key={m.id}><TableCell><strong>{m.name}</strong><p className="hint">{roles[m.role]}</p></TableCell><TableCell>{plan.length?`${count} / ${total}`:'Not assigned'}</TableCell><TableCell><div className="personal-progress"><Progress value={Math.min(100,pct)} aria-label={`${m.name}: ${count} of ${total} jobs`}/><span>{pct}%</span></div></TableCell><TableCell>{ai?`${Number(hours.toFixed(2))} / ${ai.quantity} hrs`:'—'}</TableCell><TableCell><button className="secondary" onClick={()=>setPerson(m.id)}>{manager?(plan.length?'Manage goals':'Assign goals'):'View goals'}</button></TableCell></TableRow>})}</TableBody></Table>:<Empty className="empty"><Users size={28}/><h3>Your team starts here</h3><p>Add creators and a manager to begin assigning monthly goals.</p>{data.me.role==='admin'&&<button className="primary" onClick={onTeam}>Manage team & roles</button>}</Empty>}</section>
 <div className="manager-columns"><section className="work-surface"><div className="toolbar"><h2 className="manager-heading">Ready for review</h2><span className="pill">{reviews.length}</span></div>{queue(reviews,'No submissions awaiting review for this month.')}</section><section className="work-surface"><div className="toolbar"><h2 className="manager-heading">Needs attention</h2><span className="pill">{overdue.length} overdue</span></div>{queue(overdue,'No overdue tasks due in this month.')}</section></div><p className="hint" style={{marginTop:16}}>Job progress matches each person’s assigned goal types and completion month. AI hours are tracked separately. Open a submission to approve it or request changes.</p></div>
}
