'use client';
import {useState} from 'react';
import {ChevronLeft,ChevronRight,Plus,Trash2,Target} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {Empty} from '@/components/ui/empty';
import {toast} from 'sonner';
import {kinds,localDate,goalTotal,type State,type Kind} from '@/lib/model';
type Row={kind:Kind;quantity:string;hours:string};
const colors=['#13817a','#27bdb1','#f4a019','#628dc6','#aa73be','#a6b84b'];
export default function PersonalDashboard({data,month,setMonth,onSaved,initialMemberId}:{initialMemberId?:string;data:State;month:string;setMonth:(m:string)=>void;onSaved:(s:State)=>void}){
 const manage=data.me.role==='manager';const [chosen,setChosen]=useState(initialMemberId??data.me.id);const person=(manage||data.me.role==='admin')?data.members.find(m=>m.id===chosen)??data.me:data.me;
 const [editing,setEditing]=useState(false),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const goals=(data.personalGoals??[]).filter(g=>g.member_id===person.id&&g.month===month);
 const jobs=goals.filter(g=>g.kind!=='ai_hours'),jobTarget=jobs.reduce((s,g)=>s+g.quantity,0);
 const done=data.tasks.filter(t=>t.assignee===person.id&&t.completed.startsWith(month)&&['review','approved','scheduled'].includes(t.status));
 const progress=(kind:Kind)=>goalTotal(done.filter(t=>t.kind===kind));
 const completedJobs=jobs.reduce((s,g)=>s+progress(g.kind),0),ai=goals.find(g=>g.kind==='ai_hours');
 const estimated=jobs.reduce((s,g)=>s+g.quantity*(g.hours_per_job??0),0);const missingRates=jobs.some(g=>g.hours_per_job===null);
 const date=new Date(month+'-01T12:00:00'),label=date.toLocaleDateString('en-IN',{month:'long',year:'numeric'});
 function changeMonth(n:number){setMonth(localDate(new Date(date.getFullYear(),date.getMonth()+n,1)).slice(0,7))}
 function edit(){setRows(goals.map(g=>({kind:g.kind,quantity:String(g.quantity),hours:g.hours_per_job===null?'':String(g.hours_per_job)})));setError('');setEditing(true)}
 function update(i:number,key:keyof Row,value:string){setRows(rs=>rs.map((r,n)=>n===i?{...r,[key]:value}:r))}
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'personal_goals',member_id:person.id,month,goals:rows.map(g=>({kind:g.kind,quantity:g.quantity.trim()===''?null:Number(g.quantity),hours_per_job:g.kind==='ai_hours'||g.hours.trim()===''?null:Number(g.hours)}))})});const result=await r.json() as State&{error:string};if(!r.ok)throw new Error(result.error);onSaved(result);setEditing(false);toast.success('Monthly goals saved')}catch(e){setError(e instanceof Error?e.message:'Could not save your goals.')}finally{setBusy(false)}}
 return <div className="personal-dashboard"><div className="toolbar personal-toolbar"><div className="row"><button className="quiet" aria-label="Previous goal month" onClick={()=>changeMonth(-1)}><ChevronLeft size={18}/></button><span className="month">{label}</span><button className="quiet" aria-label="Next goal month" onClick={()=>changeMonth(1)}><ChevronRight size={18}/></button><button className="secondary" onClick={()=>setMonth(localDate().slice(0,7))}>This month</button></div><div className="row">{manage&&<Select value={person.id} onValueChange={setChosen}><SelectTrigger aria-label="User whose goals to view"><SelectValue/></SelectTrigger><SelectContent>{data.members.map(m=><SelectItem key={m.id} value={m.id}>{m.name}{m.id===data.me.id?' (you)':''}</SelectItem>)}</SelectContent></Select>}{manage&&<button className="primary" onClick={edit}><Plus size={16}/>{goals.length?'Edit goals':'Assign goals'}</button>}</div></div>
 <div className="personal-banner"><span className="personal-avatar">{person.name.slice(0,1).toUpperCase()}</span><div><h2>{person.name}</h2><p>{label} · Personal goal plan</p></div><div className="personal-total"><strong>{jobTarget}</strong><span>JOBS / MONTH</span></div></div>
 {!goals.length?<Empty className="empty work-surface"><Target size={32}/><h2>No goals assigned for {label}</h2><p>{manage?'Assign this person’s goal types, monthly quantities and hours per job.':'Your manager will assign your monthly goals here.'}</p>{manage&&<button className="primary" onClick={edit}>Assign monthly goals</button>}</Empty>:<><div className="personal-grid"><section className="work-surface"><Table><TableHeader><TableRow className="personal-table-head"><TableHead>Goal type</TableHead><TableHead>Monthly goal</TableHead><TableHead>Hrs / job</TableHead><TableHead>Completed</TableHead><TableHead>Progress</TableHead></TableRow></TableHeader><TableBody>{goals.map(g=>{const n=progress(g.kind),pct=g.quantity?Math.min(100,n/g.quantity*100):0;return <TableRow key={g.id}><TableCell className={g.kind==='ai_hours'?'hours-label':''}><strong>{kinds[g.kind]}</strong></TableCell><TableCell>{g.quantity}{g.kind==='ai_hours'?' hrs':''}</TableCell><TableCell>{g.kind==='ai_hours'?'—':g.hours_per_job?.toFixed(2)??'Not set'}</TableCell><TableCell>{n}{g.kind==='ai_hours'?' hrs':''}</TableCell><TableCell><div className="personal-progress"><Progress value={pct} aria-label={`${kinds[g.kind]}: ${n} of ${g.quantity}`}/><span>{Math.round(pct)}%</span></div></TableCell></TableRow>})}</TableBody></Table></section><aside className="personal-mix work-surface"><div className="eyebrow">Goal mix · by job count</div>{jobTarget>0?<><div className="mix-bar" aria-label="Share of monthly jobs by goal type">{jobs.filter(g=>g.quantity>0).map((g,i)=><span key={g.kind} title={`${kinds[g.kind]} ${Math.round(g.quantity/jobTarget*100)}%`} style={{width:`${g.quantity/jobTarget*100}%`,background:colors[i%colors.length]}}/>)}</div><div className="mix-legend">{jobs.filter(g=>g.quantity>0).map((g,i)=><span key={g.kind}><i style={{background:colors[i%colors.length]}}/>{kinds[g.kind]} <strong>{Math.round(g.quantity/jobTarget*100)}%</strong></span>)}</div></>:<p className="hint">No job-count goals assigned.</p>}<div className="personal-summary"><span>Completed jobs</span><strong>{completedJobs} / {jobTarget}</strong></div><div className="personal-summary"><span>{missingRates?'Estimated hours (partial)':'Estimated job hours'}</span><strong>{estimated.toFixed(1)} hrs</strong></div>{ai&&<div className="ai-summary"><strong>AI Hours goal</strong><span>{progress('ai_hours')} / {ai.quantity} hrs</span></div>}</aside></div><p className="hint" style={{marginTop:16}}>Progress counts this user’s submitted, approved and scheduled work completed in {label}, across all channels. AI Hours are tracked separately from jobs.</p></>}
 <Dialog open={editing} onOpenChange={v=>{if(!busy)setEditing(v)}}><DialogContent className="dialog-body personal-editor"><DialogTitle>Monthly goals · {person.name}</DialogTitle><DialogDescription>{label}. Set this person’s goals across all channels. Hours per job are optional estimates.</DialogDescription>{error&&<div className="form-error" role="alert">{error}</div>}<form onSubmit={e=>{e.preventDefault();void save()}} className="form">{rows.map((r,i)=><div className="personal-editor-row" key={i}><label>Goal type<Select value={r.kind} onValueChange={v=>update(i,'kind',v)}><SelectTrigger aria-label={`Goal type ${i+1}`}><SelectValue/></SelectTrigger><SelectContent>{Object.entries(kinds).map(([value,label])=><SelectItem value={value} key={value}>{label}</SelectItem>)}</SelectContent></Select></label><label>{r.kind==='ai_hours'?'Hours':'Jobs'}<input required type="number" min="0" max="100000" step={r.kind==='ai_hours'?'0.01':'1'} value={r.quantity} onChange={e=>update(i,'quantity',e.target.value)}/></label><label>Hrs / job<input aria-label={`Hours per job ${i+1}`} type="number" min="0" max="1000" step="0.01" disabled={r.kind==='ai_hours'} value={r.kind==='ai_hours'?'':r.hours} onChange={e=>update(i,'hours',e.target.value)}/></label><button type="button" className="quiet" aria-label={`Remove goal ${i+1}`} onClick={()=>setRows(rs=>rs.filter((_,n)=>n!==i))}><Trash2 size={17}/></button></div>)}<button type="button" className="secondary" disabled={rows.length>=Object.keys(kinds).length} onClick={()=>{const kind=Object.keys(kinds).find(k=>!rows.some(r=>r.kind===k)) as Kind;if(kind)setRows([...rows,{kind,quantity:'',hours:''}])}}><Plus size={15}/>Add goal type</button>{!rows.length&&<button type="button" className="quiet" onClick={()=>setRows([{kind:'shoot',quantity:'8',hours:'4'},{kind:'post',quantity:'100',hours:'0.5'},{kind:'story',quantity:'120',hours:'0.5'},{kind:'ai_hours',quantity:'4',hours:''}])}>Fill Ashwin’s reference goals</button>}<div className="hint">AI Hours are an hours target. They do not increase the job count. Clearing all rows removes this person’s plan for this month.</div><div className="actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save monthly goals'}</button></div></form></DialogContent></Dialog></div>
}
