"use client";
import {useEffect,useRef,useState,type FormEvent,type CSSProperties} from 'react';
import {CalendarDays,Plus,CheckCheck,Target,Layers,Users,ArrowUpRight,ChevronLeft,ChevronRight,ListTodo,LayoutGrid,ImageIcon,Film,PanelsTopLeft,Link as LinkIcon,ExternalLink,Copy,Check,RefreshCw,Clock3,FolderOpen,ShieldCheck} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Progress} from '@/components/ui/progress';
import {Empty} from '@/components/ui/empty';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {kinds,goalGroups,goalGroup,goalStyle,goalTotal,roles,statuses,driveId,localDate,type State,type Task,type Channel,type Kind} from '@/lib/model';
const typeIcons={graphic:ImageIcon,video:Film,uiux:PanelsTopLeft};
const nav=[{id:'calendar',label:'Calendar',icon:CalendarDays},{id:'tasks',label:'Tasks',icon:ListTodo},{id:'targets',label:'Monthly targets',icon:Target},{id:'channels',label:'Channels',icon:Layers},{id:'team',label:'Team & roles',icon:Users}];
function Pick({label,value,onChange,options}:{label:string;value:string;onChange:(x:string)=>void;options:{value:string;label:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="select-control"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function Nothing({title,description,children}:{title:string;description:string;children?:React.ReactNode}){return <Empty className="empty"><span className="empty-icon"><Layers size={25}/></span><h2>{title}</h2><p>{description}</p>{children}</Empty>}
function SideNav({view,setView,data,filter,setFilter}:{view:string;setView:(x:string)=>void;data:State|null;filter:string;setFilter:(x:string)=>void}){const {setOpenMobile}=useSidebar();function go(v:string){setView(v);setOpenMobile(false)}return <><div className="brand"><span className="brand-mark"><Layers size={21}/></span>studio<span style={{color:'#aedcc4'}}>.</span></div><div className="side-label">Workspace</div><nav className="side-nav" aria-label="Workspace">{nav.filter(n=>n.id!=='team'||data?.me.role==='admin').map(n=><button className={view===n.id?'active':''} key={n.id} onClick={()=>go(n.id)}><n.icon size={18}/>{n.label}{n.id==='tasks'&&data&&<span className="count">{data.tasks.filter(t=>!['approved','scheduled'].includes(t.status)).length}</span>}</button>)}</nav><div className="side-label" style={{marginTop:23}}>Your channels</div><nav className="side-nav" aria-label="Channels"><button className={filter==='all'?'active':''} onClick={()=>{setFilter('all');go('calendar')}}><LayoutGrid size={16}/>All channels</button>{data?.channels.map(c=><button key={c.id} className={filter===c.id?'active':''} onClick={()=>{setFilter(c.id);go('calendar')}}><span className="side-channel"/>{c.name}</button>)}</nav><div className="side-bottom"><strong>Your creative workspace</strong><br/>Plan. Create. Deliver.<br/><a className="signout" href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a></div></>}
function Artwork({task}:{task:Task}){const [failed,setFailed]=useState(false);const Icon=typeIcons[goalStyle(task.kind)];const id=driveId(task.drive_url);return <div className={'art-preview '+goalStyle(task.kind)}><Icon size={32}/>{id&&!failed&&<img src={`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w480`} alt={task.title} loading="lazy" onError={()=>setFailed(true)}/>}</div>}
export default function Studio(){
const [data,setData]=useState<State|null>(null),[loadError,setLoadError]=useState(''),[auth,setAuth]=useState(0),[loading,setLoading]=useState(true);
const [view,setView]=useState('calendar'),[mode,setMode]=useState('calendar'),[month,setMonth]=useState(localDate().slice(0,7)),[filter,setFilter]=useState('all'),[statusFilter,setStatusFilter]=useState('all'),[group,setGroup]=useState('content');
const [modal,setModal]=useState(''),[selected,setSelected]=useState<Task|null>(null),[form,setForm]=useState<Record<string,string>>({}),[formError,setFormError]=useState(''),[busy,setBusy]=useState(false),[showPreview,setShowPreview]=useState(false);
const stateRef=useRef(data);stateRef.current=data;
async function reload(){setLoading(true);setLoadError('');try{const r=await fetch('/api/workspace');const s=await r.json() as State & {error:string};if(!r.ok){setAuth(r.status);throw new Error(s.error)}setData(s);setAuth(0)}catch(e){setLoadError(e instanceof Error?e.message:'Could not load workspace.')}finally{setLoading(false)}}
useEffect(()=>{void reload()},[]);
useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,opts:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'list_visible_tasks',description:'Read the signed-in user’s visible creative tasks. Does not modify data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');if(!stateRef.current)throw new Error('Sign in and load the workspace first.');return {tasks:stateRef.current.tasks}}},{signal:life.signal})).catch(console.error)}catch(e){console.error(e)}return()=>life.abort()},[]);
const admin=data?.me.role==='admin',manage=admin||data?.me.role==='manager',create=manage||data?.me.role==='creator';
const visible=(data?.tasks??[]).filter(t=>(filter==='all'||t.channel_id===filter)&&goalGroup(t.kind)===group);
const completed=visible.filter(t=>['review','approved','scheduled'].includes(t.status)&&t.completed.startsWith(month));
const monthTasks=visible.filter(t=>t.due.startsWith(month));
const totalTarget=(data?.targets??[]).filter(t=>t.month===month&&goalGroup(t.kind)===group&&(filter==='all'||t.channel_id===filter)).reduce((a,t)=>a+t.quantity,0);
const ready=visible.filter(t=>t.status==='approved'&&t.completed.startsWith(month));
const channelName=(id:string)=>data?.channels.find(c=>c.id===id)?.name??'Channel';const memberName=(id:string)=>data?.members.find(m=>m.id===id)?.name??'Team member';
const monthDate=new Date(month+'-01T12:00:00'),monthLabel=monthDate.toLocaleDateString('en-IN',{month:'long',year:'numeric'});
function moveMonth(n:number){setMonth(localDate(new Date(monthDate.getFullYear(),monthDate.getMonth()+n,1)).slice(0,7))}
function open(name:string,values:Record<string,string>={},task:Task|null=null){setFormError('');setForm(values);setSelected(task);setShowPreview(false);setModal(name)}
function newTask(){if(!data?.channels.length){if(admin)open('channel',{name:'',folder:''});else toast.error('Ask your admin to add a channel first.');return}open('task',{title:'',channel_id:filter==='all'?data.channels[0].id:filter,kind:Object.keys(kinds).find(k=>goalGroup(k)===group)||'reels',due:localDate(),assignee:data.me.id,notes:''})}
function details(t:Task){open('detail',{},t)}
function f(key:string,value:string){setForm(v=>({...v,[key]:value}))}
async function mutate(payload:Record<string,unknown>,close=true){setBusy(true);setFormError('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await r.json() as State & {error:string};if(!r.ok)throw new Error(result.error);setData(result);if(typeof payload.kind==='string')setGroup(goalGroup(payload.kind));if(close)setModal('');toast.success('Workspace updated');return true}catch(e){setFormError(e instanceof Error?e.message:'Could not save. Please retry.');return false}finally{setBusy(false)}}
async function submit(e:FormEvent){e.preventDefault();const payload:Record<string,unknown>={...form,action:modal};if(modal==='target')payload.quantity=Number(form.quantity);if(modal==='submit'&&selected?.kind==='ai_hours')payload.completed_hours=Number(form.completed_hours);if(selected){payload.id=selected.id;payload.version=selected.version}await mutate(payload)}
async function copyHandoff(items:Task[]){const text=items.map(t=>`${t.title}\nChannel: ${channelName(t.channel_id)}\nType: ${kinds[t.kind]}\nCompleted: ${t.completed}\n${t.drive_url}${t.notes?'\nNotes: '+t.notes:''}`).join('\n\n———\n\n');try{await navigator.clipboard.writeText(text);toast.success('Handoff copied. Paste it to your scheduling team.')}catch{open('copy',{text})}}
const title={calendar:'Deliverables calendar',tasks:'Your task list',targets:'Monthly targets',channels:'Your channels',team:'Team & roles'}[view];
const subtitle={calendar:'Completed work, organized by channel and completion date.',tasks:'Keep the next deliverable moving, from brief to approval.',targets:'Set the pace for each channel. See how the month is taking shape.',channels:'Give every channel its own tasks, targets, and Drive folder.',team:'The right access for every step of your creative workflow.'}[view];
const start=new Date(monthDate);start.setDate(1-((start.getDay()+6)%7));const dayCount=Math.ceil((((monthDate.getDay()+6)%7)+new Date(monthDate.getFullYear(),monthDate.getMonth()+1,0).getDate())/7)*7;
const list=monthTasks.filter(t=>statusFilter==='all'||t.status===statusFilter);
if(auth===401||auth===403)return <main className="access-card"><span className="brand-mark"><Layers/></span><h1>Your creative workspace</h1><p>{auth===401?'Sign in to manage your channels, creative tasks and completed deliverables.':loadError}</p><a className="primary" href={auth===401?'/signin-with-chatgpt?return_to=/':'/signout-with-chatgpt?return_to=/'} target="_top">{auth===401?'Sign in with ChatGPT':'Use a different account'}<ArrowUpRight size={16}/></a></main>;
return <SidebarProvider style={{'--sidebar-width':'230px'} as CSSProperties}><Sidebar><SidebarContent><SideNav view={view} setView={setView} data={data} filter={filter} setFilter={setFilter}/></SidebarContent></Sidebar><main className="app-main"><header className="topbar"><div className="crumb"><SidebarTrigger/>Workspace <ChevronRight size={14}/><span>{nav.find(n=>n.id===view)?.label}</span></div><div className="profile"><button className="quiet" onClick={()=>void reload()} aria-label="Refresh workspace" disabled={loading}><RefreshCw size={16}/></button><span className="avatar">{data?.me.name.slice(0,2).toUpperCase()||'ST'}</span><span className="user-name">{data?.me.name||'My workspace'}</span>{data&&<span className="pill">{roles[data.me.role]}</span>}</div></header><div className="content"><div className="page-head"><div><div className="eyebrow">Your work, in view</div><h1>{title}</h1><p className="subtext">{subtitle}</p></div>{data&&(view==='team'?admin&&<button className="primary" onClick={()=>open('member',{name:'',email:'',role:'creator'})}><Plus size={17}/>Add member</button>:view==='channels'?admin&&<button className="primary" onClick={()=>open('channel',{name:'',folder:''})}><Plus size={17}/>Add channel</button>:view==='targets'?admin&&<button className="primary" disabled={!data.channels.length} onClick={()=>open('target',{channel_id:filter==='all'?data.channels[0].id:filter,month,kind:Object.keys(kinds).find(k=>goalGroup(k)===group)||'reels',quantity:'0'})}><Plus size={17}/>Set target</button>:create&&<button className="primary" onClick={newTask}><Plus size={17}/>New task</button>)}</div>
{loadError&&<div className="form-error" role="alert">{loadError} <button className="quiet" onClick={()=>void reload()}>Try again</button></div>}
{loading&&!data?<Nothing title="Loading your workspace" description="Getting your channels, tasks and monthly targets."/>:<>
{['calendar','tasks','targets'].includes(view)&&<><div className="stats">{[{label:'Monthly target',value:totalTarget,icon:Target,note:totalTarget?(group==='hours'?'Hours planned':goalGroups[group as keyof typeof goalGroups]+' jobs planned'):'Set a target to track progress'},{label:group==='hours'?'Hours completed':'Completed',value:goalTotal(completed),icon:CheckCheck,note:'Submitted, approved or scheduled'},{label:'In progress',value:monthTasks.filter(t=>['progress','changes'].includes(t.status)).length,icon:Clock3,note:'Tasks due this month'},{label:'Ready to schedule',value:ready.length,icon:ArrowUpRight,note:'Approved and ready for handoff'}].map(s=><div className="stat" key={s.label}><div className="stat-label"><s.icon size={16}/>{s.label}</div><div className="stat-value">{s.value}{['Completed','Hours completed'].includes(s.label)&&totalTarget>0&&<span style={{fontSize:14,fontWeight:400,color:'#6b7d83',letterSpacing:0}}>/ {totalTarget}</span>}</div><div className="stat-note">{s.note}</div></div>)}</div>{data?.me.role==='creator'&&<p className="hint" style={{marginBottom:14}}>Task counts show your assigned work. Monthly targets are for the whole channel.</p>}</>}
{['calendar','tasks','targets'].includes(view)&&<div className="goal-category-bar"><label>Goal category<Pick label="Goal category" value={group} onChange={setGroup} options={Object.entries(goalGroups).map(([value,label])=>({value,label}))}/></label><p className="hint">{group==='content'?'Count each original piece once per brand, even when shared on Instagram and Facebook.':group==='ads'?'Ads are tracked separately from channel content. Choose Ads when the subtype is unknown.':group==='hours'?'AI Hours are measured in hours, never added to content or job totals.':group==='unclassified'?'The reference leaves longer, FFC and New Creative unclassified. Their totals stay separate.':'Track these goals separately from the content and ads totals.'}</p></div>}<section className="work-surface">
{['calendar','tasks','targets'].includes(view)&&<div className="toolbar"><div className="row"><button className="quiet" aria-label="Previous month" onClick={()=>moveMonth(-1)}><ChevronLeft size={18}/></button><span className="month">{monthLabel}</span><button className="quiet" aria-label="Next month" onClick={()=>moveMonth(1)}><ChevronRight size={18}/></button><button className="secondary" onClick={()=>setMonth(localDate().slice(0,7))}>This month</button></div><div className="row"><Pick label="Filter by channel" value={filter} onChange={setFilter} options={[{value:'all',label:'All channels'},...(data?.channels??[]).map(c=>({value:c.id,label:c.name}))]}/>{view==='tasks'&&<Pick label="Filter by status" value={statusFilter} onChange={setStatusFilter} options={[{value:'all',label:'All statuses'},...Object.entries(statuses).map(([value,label])=>({value,label}))]}/>}</div></div>}
{!data?.channels.length&&view!=='team'&&<div className="workspace-guide"><Layers size={23}/><p><strong>Start with your first channel.</strong><br/>{admin?'Add a channel, set your monthly targets, and plan your tasks.':'Your admin can add channels to get the workspace started.'}</p>{admin&&<button className="secondary" style={{marginLeft:'auto'}} onClick={()=>open('channel',{name:'',folder:''})}><Plus size={15}/>Add channel</button>}</div>}
{view==='calendar'&&<Tabs value={mode} onValueChange={setMode}><div className="toolbar" style={{paddingTop:12,paddingBottom:12}}><TabsList><TabsTrigger value="calendar"><CalendarDays size={15}/>Calendar</TabsTrigger><TabsTrigger value="gallery"><LayoutGrid size={15}/>Gallery</TabsTrigger></TabsList><div className="row"><span className="meta">{completed.length} {group==='hours'?'time entries':'completed jobs'}</span>{ready.length>0&&(manage||data?.me.role==='scheduler')&&<button className="secondary" onClick={()=>void copyHandoff(ready)}><Copy size={14}/>Copy handoff</button>}</div></div><TabsContent value="calendar" style={{margin:0}}><div className="calendar-scroll"><div className="calendar">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><div className="weekday" key={d}>{d}</div>)}{Array.from({length:dayCount},(_,i)=>{const date=new Date(start);date.setDate(start.getDate()+i);const key=localDate(date),items=completed.filter(t=>t.completed===key),today=key===localDate();return <div className={'day '+(!key.startsWith(month)?'out ':'')+(today?'today':'')} key={key}><div className="date-num"><span className={today?'today-num':''}>{date.getDate()}</span>{items.length>0&&<span className="meta">{items.length}</span>}</div>{items.map(t=><button className={'cal-task '+goalStyle(t.kind)} onClick={()=>details(t)} key={t.id}><strong>{t.title}</strong><span>{channelName(t.channel_id)} · {statuses[t.status]}</span></button>)}</div>})}</div></div></TabsContent><TabsContent value="gallery" style={{margin:0}}>{completed.length?<div className="grid-cards">{completed.map(t=><button className="deliverable" key={t.id} onClick={()=>details(t)}><Artwork task={t}/><div className="card-body"><div className="meta">{channelName(t.channel_id)} · {t.completed}</div><h3>{t.title}</h3><span className={'pill '+t.status}>{statuses[t.status]}</span></div></button>)}</div>:<Nothing title="Your work will look good here" description="Submit a task with its Google Drive link and completion date to add it to this gallery.">{create&&<button className="secondary" onClick={()=>setView('tasks')}>Go to tasks <ArrowUpRight size={15}/></button>}</Nothing>}</TabsContent><div className="surface-footer"><span>Organized by completion date · Drive access controls previews</span><div className="legend"><span>{goalGroups[group as keyof typeof goalGroups]}</span></div></div></Tabs>}
{view==='tasks'&&(list.length?<><div className="list-task list-header"><span>Task / due date</span><span className="channel-col">Channel</span><span className="assignee-col">Assigned to</span><span>Status</span></div>{list.map(t=><button className="list-task" key={t.id} onClick={()=>details(t)}><div><strong>{t.title}</strong><p>{kinds[t.kind]} · Due {t.due}{t.due<localDate()&&['planned','progress','changes'].includes(t.status)?' · Overdue':''}</p></div><span className="channel-col" style={{fontSize:14}}>{channelName(t.channel_id)}</span><span className="assignee-col" style={{fontSize:14}}>{memberName(t.assignee)}</span><span className={'pill '+t.status}>{statuses[t.status]}</span></button>)}</>:<Nothing title="A little planning goes a long way" description="No tasks match this month and filter. Add a task with a channel, goal type, assignee and due date.">{create&&<button className="primary" onClick={newTask}><Plus size={16}/>Create a task</button>}</Nothing>)}
{view==='targets'&&<div className="targets">{data?.channels.filter(c=>filter==='all'||c.id===filter).map(c=><article className="target-card" key={c.id}><div className="row"><span className="brand-mark"><Layers size={17}/></span><h3 style={{margin:0}}>{c.name}</h3></div>{Object.entries(kinds).filter(([kind])=>goalGroup(kind)===group).map(([kind,label])=>{const target=data.targets.find(t=>t.month===month&&t.channel_id===c.id&&t.kind===kind)?.quantity??0;const count=goalTotal(completed.filter(t=>t.channel_id===c.id&&t.kind===kind));return <div className="target-line" key={kind}><div className="row spread"><span>{label}</span><strong>{count} / {target||'—'}{kind==='ai_hours'?' hrs':''}</strong></div><Progress aria-label={`${label}: ${count} of ${target}`} value={target?Math.min(100,count/target*100):0}/>{admin&&<button className="quiet" style={{fontSize:12,padding:'9px 0 0'}} onClick={()=>open('target',{channel_id:c.id,month,kind,quantity:String(target)})}>{target?'Edit target':'Set target'}</button>}</div>})}</article>)}</div>}
{view==='channels'&&<div className="targets">{data?.channels.map(c=><article className="target-card" key={c.id}><div className="row spread"><span className="brand-mark"><Layers size={20}/></span>{admin&&<button className="quiet" onClick={()=>open('channel',{id:c.id,name:c.name,folder:c.folder})}>Edit</button>}</div><h3 style={{marginTop:20,marginBottom:8}}>{c.name}</h3><p className="meta">{data.tasks.filter(t=>t.channel_id===c.id).length} visible tasks</p><div className="actions" style={{marginTop:20}}><button className="secondary" onClick={()=>{setFilter(c.id);setView('tasks')}}>View tasks</button>{c.folder&&<a className="quiet" href={c.folder} target="_blank" rel="noreferrer"><FolderOpen size={16}/>Drive folder</a>}</div></article>)}</div>}
{view==='team'&&admin&&<><div className="workspace-guide"><ShieldCheck size={23}/><p><strong>Four roles. One clear workflow.</strong><br/>Add each teammate’s ChatGPT sign-in email. Then share the app link with them.</p></div><div className="targets" style={{gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))'}}>{Object.entries(roles).map(([role,label])=><div key={role}><h3 style={{fontSize:14,fontWeight:650}}>{label}</h3><p className="hint" style={{marginTop:6}}>{{admin:'Manages channels, targets, people and all work.',manager:'Assigns tasks, reviews submissions and approves work.',creator:'Creates and updates own tasks, submits Drive links.',scheduler:'Views approved work and records scheduling dates.'}[role]}</p></div>)}</div>{data?.members.map(m=><div className="list-task" key={m.id} style={{gridTemplateColumns:'minmax(160px,2fr) 1fr auto'}}><div><strong>{m.name}{m.id===data.me.id?' (you)':''}</strong><p>{m.email}</p></div><span className="pill">{roles[m.role]}</span><div className="row"><span className="meta">{m.user_id?'Joined':'Awaiting sign-in'}</span><button className="quiet" onClick={()=>open('member',{name:m.name,email:m.email,role:m.role})}>Edit</button>{m.id!==data.me.id&&<button className="quiet" onClick={()=>open('remove_member',{id:m.id,name:m.name})}>Remove</button>}</div></div>)}<p className="hint" style={{padding:20}}>Adding a member grants app permissions; it does not send an email. The Site’s audience must also allow teammates to open it. Drive files keep their own sharing permissions.</p></>}
</section></>}
</div></main><Toaster richColors theme="light"/>
<AlertDialog open={modal==='remove_member'} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><AlertDialogContent><AlertDialogTitle>Remove team member</AlertDialogTitle><AlertDialogDescription>Remove {form.name} from this workspace? Reassign their tasks first.</AlertDialogDescription>{formError&&<p role="alert" className="form-error">{formError}</p>}<div className="actions"><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><button className="primary" disabled={busy} onClick={()=>void mutate({action:'remove_member',id:form.id})}>Remove member</button></div></AlertDialogContent></AlertDialog><Dialog open={!!modal&&modal!=='remove_member'} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className="dialog-body"><DialogTitle>{modal==='detail'?selected?.title:({task:form.id?'Edit task':'Create a task',channel:form.id?'Edit channel':'Add a channel',target:'Set monthly target',member:'Team member',submit:'Submit deliverable',changes:'Request changes',schedule:'Mark as scheduled',remove_member:'Remove team member',copy:'Copy handoff'}[modal]??'Workspace')}</DialogTitle><DialogDescription>{modal==='detail'?'Track the brief, deliverable and review in one place.':modal==='submit'?'Paste the Drive link for the finished file. The completion date places it on the calendar.':modal==='channel'?'Create a home for this channel’s work.':modal==='member'?'Use the exact email your teammate uses to sign in with ChatGPT.':'Your changes are saved to the shared workspace.'}</DialogDescription>
{formError&&<div className="form-error" role="alert">{formError}</div>}
{modal==='detail'&&selected?<><dl className="detail-grid"><div><dt>Channel</dt><dd>{channelName(selected.channel_id)}</dd></div><div><dt>Status</dt><dd><span className={'pill '+selected.status}>{statuses[selected.status]}</span></dd></div><div><dt>Goal type</dt><dd>{kinds[selected.kind]}{selected.kind==='ai_hours'&&selected.completed?' · '+selected.completed_hours+' hrs':''}</dd></div><div><dt>Assigned to</dt><dd>{memberName(selected.assignee)}</dd></div><div><dt>Due date</dt><dd>{selected.due}</dd></div>{selected.completed&&<div><dt>Completed</dt><dd>{selected.completed}</dd></div>}{selected.scheduled&&<div><dt>Scheduling date</dt><dd>{selected.scheduled}</dd></div>}</dl>{selected.notes&&<p style={{whiteSpace:'pre-wrap',fontSize:14}}>{selected.notes}</p>}{selected.feedback&&<div className="notice"><strong>Review feedback</strong><p style={{marginTop:6,whiteSpace:'pre-wrap'}}>{selected.feedback}</p></div>}{selected.drive_url&&<><a className="secondary" href={selected.drive_url} target="_blank" rel="noreferrer"><LinkIcon size={16}/>Open deliverable in Drive<ExternalLink size={15}/></a>{driveId(selected.drive_url)&&<button className="quiet" onClick={()=>setShowPreview(!showPreview)}>{showPreview?'Hide':'Show'} Drive preview</button>}{showPreview&&<iframe title="Google Drive deliverable preview" className="drive-preview" src={`https://drive.google.com/file/d/${encodeURIComponent(driveId(selected.drive_url)!)}/preview`} allow="fullscreen"/>}<p className="hint">If the preview is unavailable, open Drive and check that the file is shared with your team.</p></>}
<div className="actions">{create&&['planned','progress','changes','review'].includes(selected.status)&&<><button className="primary" onClick={()=>open('submit',{drive_url:selected.drive_url,completed:selected.completed||localDate(),completed_hours:String(selected.completed_hours||'')},selected)}><LinkIcon size={15}/>{selected.drive_url?'Update submission':'Submit deliverable'}</button><button className="secondary" onClick={()=>open('task',{id:selected.id,title:selected.title,channel_id:selected.channel_id,kind:selected.kind,due:selected.due,assignee:selected.assignee,notes:selected.notes},selected)}>Edit task</button>{['planned','changes'].includes(selected.status)&&<button className="secondary" disabled={busy} onClick={()=>void mutate({action:'start',id:selected.id,version:selected.version})}>Start work</button>}</>}{manage&&selected.status==='review'&&<><button className="primary" disabled={busy} onClick={()=>void mutate({action:'approve',id:selected.id,version:selected.version})}><Check size={15}/>Approve</button><button className="secondary" onClick={()=>open('changes',{feedback:''},selected)}>Request changes</button></>}{(manage||data?.me.role==='scheduler')&&selected.status==='approved'&&<><button className="primary" onClick={()=>open('schedule',{scheduled:localDate()},selected)}>Mark scheduled</button><button className="secondary" onClick={()=>void copyHandoff([selected])}><Copy size={15}/>Copy handoff</button></>}</div></>:modal==='copy'?<><textarea readOnly value={form.text} aria-label="Handoff text" style={{minHeight:250}} onFocus={e=>e.target.select()}/><p className="hint">Select and copy this text to share with your scheduling team.</p></>:<form onSubmit={submit} className="form">
{modal==='channel'&&<><label>Channel name<input required maxLength={80} value={form.name||''} onChange={e=>f('name',e.target.value)} placeholder="e.g. Brand Instagram"/></label><label>Google Drive folder <span className="hint">Optional</span><input type="url" value={form.folder||''} onChange={e=>f('folder',e.target.value)} placeholder="https://drive.google.com/drive/folders/…"/></label></>}
{modal==='task'&&<div className="form-grid"><label className="full">Task title<input required maxLength={160} value={form.title||''} onChange={e=>f('title',e.target.value)} placeholder="e.g. Product launch carousel"/></label><label>Channel<Pick label="Task channel" value={form.channel_id} onChange={v=>f('channel_id',v)} options={(data?.channels??[]).map(c=>({value:c.id,label:c.name}))}/></label><label>Goal type<Pick label="Goal type" value={form.kind} onChange={v=>f('kind',v)} options={Object.entries(kinds).map(([value,label])=>({value,label}))}/></label><label>Due date<input type="date" required value={form.due||''} onChange={e=>f('due',e.target.value)}/></label>{manage&&<label>Assigned to<Pick label="Assigned to" value={form.assignee} onChange={v=>f('assignee',v)} options={(data?.members??[]).filter(m=>m.role!=='scheduler').map(m=>({value:m.id,label:m.name}))}/></label>}<label className="full">Brief / notes<textarea maxLength={3000} value={form.notes||''} onChange={e=>f('notes',e.target.value)} placeholder="What needs to be created?"/></label></div>}
{modal==='target'&&<><label>Channel<Pick label="Target channel" value={form.channel_id} onChange={v=>f('channel_id',v)} options={(data?.channels??[]).map(c=>({value:c.id,label:c.name}))}/></label><div className="form-grid"><label>Month<input required type="month" value={form.month||''} onChange={e=>f('month',e.target.value)}/></label><label>{form.kind==='ai_hours'?'Target hours (whole hours)':'Target jobs'}<input type="number" required min={0} max={100000} step={1} value={form.quantity||''} onChange={e=>f('quantity',e.target.value)}/></label></div><label>Goal type<Pick label="Target goal type" value={form.kind} onChange={v=>f('kind',v)} options={Object.entries(kinds).map(([value,label])=>({value,label}))}/></label></>}
{modal==='member'&&<><label>Name<input required maxLength={100} value={form.name||''} onChange={e=>f('name',e.target.value)}/></label><label>ChatGPT sign-in email<input type="email" required value={form.email||''} onChange={e=>f('email',e.target.value)}/></label><label>Role<Pick label="Member role" value={form.role} onChange={v=>f('role',v)} options={Object.entries(roles).map(([value,label])=>({value,label}))}/></label><p className="hint">They can join using this email once the Site audience allows them access. No email is sent.</p></>}
{modal==='submit'&&<>{selected?.kind==='ai_hours'&&<label>Completed AI hours<input type="number" required min={0.01} max={744} step={0.01} value={form.completed_hours||''} onChange={e=>f('completed_hours',e.target.value)}/></label>}<label>Google Drive deliverable link {selected?.kind==='ai_hours'?'(optional)':''}<input type="url" required={selected?.kind!=='ai_hours'} value={form.drive_url||''} onChange={e=>f('drive_url',e.target.value)} placeholder="https://drive.google.com/file/d/…/view"/></label><label>Completion date<input type="date" required max={localDate()} value={form.completed||''} onChange={e=>f('completed',e.target.value)}/></label><p className="hint">Use a file link for a visual preview. Folder and Google Docs links can still be opened in Drive. Submitting sends the task to review.</p></>}
{modal==='changes'&&<label>Feedback<textarea required maxLength={2000} value={form.feedback||''} onChange={e=>f('feedback',e.target.value)} placeholder="Describe what needs to change."/></label>}
{modal==='schedule'&&<><label>Scheduled publishing date<input required type="date" value={form.scheduled||''} onChange={e=>f('scheduled',e.target.value)}/></label><p className="hint">This records the date. It does not publish to social media or connect to a scheduling service.</p></>}
{modal==='remove_member'&&<p>Remove {form.name}’s access to this workspace? Members with assigned tasks must be reassigned first.</p>}
<div className="actions" style={{justifyContent:'flex-end'}}><button type="button" className="secondary" disabled={busy} onClick={()=>setModal('')}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':modal==='submit'?'Submit for review':modal==='remove_member'?'Remove member':'Save changes'}</button></div></form>}
</DialogContent></Dialog>
</SidebarProvider>}


