'use client';
import {ArrowUpRight,Target,CheckCheck,Clock3,MessageSquare,FolderOpen} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Empty} from '@/components/ui/empty';
import {credit,type ManagerState,type Plan,type Submission} from '@/lib/manager';
import type {Task as DailyTask} from './daily-planner';

export default function UserDashboard({data,plans,submissions,readyTasks,onSubmitTask,onDaily,onRevise,onHistory}:{data:ManagerState;plans:Plan[];submissions:Submission[];readyTasks:DailyTask[];onSubmitTask:(task:DailyTask)=>void;onDaily:()=>void;onRevise:(s:Submission)=>void;onHistory:()=>void}){
 const type=(id:string)=>data.types.find(t=>t.id===id);
 const jobs=plans.filter(p=>type(p.type_id)?.unit==='jobs'&&p.target>0),target=jobs.reduce((n,p)=>n+p.target,0),done=jobs.reduce((n,p)=>n+credit(p.id,submissions),0);
 const changes=submissions.filter(s=>s.status==='changes'),pending=submissions.filter(s=>s.status==='review').length;
 const remaining=jobs.reduce((n,p)=>n+Math.max(0,p.target-credit(p.id,submissions)),0);
 return <div className="user-dashboard"><section className="user-welcome"><div><div className="eyebrow">Your month, your progress</div><h2>Hello, {data.me.name.split(' ')[0]}.</h2><p>{plans.length?'Here’s what you’re working toward. Every submission brings you closer.':'Your workspace is ready. Your team lead will assign your monthly goals here.'}</p><span className="user-job">{data.me.job}</span></div><div className="user-month-total"><strong>{done}<span> / {target}</span></strong><p>jobs delivered this goal month</p><Progress value={target?Math.min(100,done/target*100):0} aria-label={`${done} of ${target} jobs delivered`}/></div></section>
 <div className="stats">{[{name:'Jobs remaining',value:remaining,icon:Target,note:'Against each assigned target'},{name:'Awaiting review',value:pending,icon:Clock3,note:'Already counted in progress'},{name:'Approved',value:submissions.filter(s=>s.status==='approved').length,icon:CheckCheck,note:'Submissions signed off'},{name:'Changes requested',value:changes.length,icon:MessageSquare,note:'Revise to restore progress'}].map(s=><article className="stat" key={s.name}><div className="stat-label"><s.icon size={16}/>{s.name}</div><strong className="stat-value">{s.value}</strong><p className="stat-note">{s.note}</p></article>)}</div>
 <div className="user-layout"><section className="work-surface"><div className="toolbar"><div><h2 className="manager-heading">My monthly goals</h2><p className="hint">Assigned by your team lead · Jobs and hours stay separate</p></div><span className="pill">{plans.length} goal types</span></div>{plans.length?<div className="user-goal-list">{plans.map(p=>{const t=type(p.type_id),n=credit(p.id,submissions),unmetered=p.target===0,pct=unmetered?0:Math.round(n/p.target*100),ready=readyTasks.filter(task=>task.category===t?.name&&task.work_date.slice(0,7)===p.month);return <article className="user-goal" key={p.id}><div className="row spread"><span className="row"><span className="user-goal-icon"><Target size={18}/></span><strong>{t?.name}</strong></span><span className="hint">{unmetered?'No monthly target':pct>=100?'Target reached':`${Math.max(0,Math.round((p.target-n)*100)/100)} ${t?.unit} left`}</span></div><div className="row spread"><div className="user-goal-number">{n}<span>{unmetered?` ${t?.unit} recorded`:` / ${p.target} ${t?.unit}`}</span></div>{!unmetered&&<span className="hint">{pct}%</span>}</div>{!unmetered&&<Progress value={Math.min(100,pct)} aria-label={`${t?.name}: ${n} of ${p.target} ${t?.unit}`}/>}<div className="goal-ready"><strong>Completed · ready to submit ({ready.length})</strong>{ready.length?ready.map(task=><div className="goal-ready-item" key={task.id}><span>{task.title}<small>{task.work_date}</small></span><button className="secondary" onClick={()=>onSubmitTask(task)}>Submit output <ArrowUpRight size={14}/></button></div>):<p className="hint">Mark a {t?.name} task completed in Daily tasks to see it here.</p>}<button className="quiet" onClick={onDaily}>Open daily tasks <ArrowUpRight size={14}/></button></div></article>})}</div>:<Empty className="empty"><Target size={30}/><h3>No goals assigned yet</h3><p>Select another month or ask your manager to set your targets.</p></Empty>}</section>
 <aside className="work-surface user-feedback"><div className="toolbar"><h2 className="manager-heading">Needs your attention</h2><span className="pill">{changes.length}</span></div>{changes.length?<div className="user-feedback-list">{changes.map(s=><article key={s.id}><span className="pill changes">Changes requested</span><h3>{s.title}</h3><p>{s.feedback}</p>{s.url&&<a className="secondary" href={s.url} target="_blank" rel="noopener noreferrer">Open in Drive <ArrowUpRight size={14}/></a>}<button className="primary" onClick={()=>onRevise(s)}>Revise & resubmit</button></article>)}</div>:<Empty className="empty"><CheckCheck size={28}/><h3>You’re all caught up</h3><p>Feedback from your team lead will appear here when work needs a revision.</p></Empty>}<p className="fresh-footnote">Work needing changes pauses its progress credit. Resubmit the same entry after making the requested changes.</p></aside></div>
 <section className="work-surface user-recent"><div className="toolbar"><div><h2 className="manager-heading">Recent work</h2><p className="hint">Deliverables linked to this goal month</p></div><button className="quiet" onClick={onHistory}>All submissions <ArrowUpRight size={14}/></button></div>{submissions.length?<div className="user-gallery">{submissions.slice(0,6).map(s=><article key={s.id}><div className="user-file"><FolderOpen size={30}/><span>{type(plans.find(p=>p.id===s.plan_id)?.type_id||'')?.name}</span></div><div className="user-file-body"><span className={'pill '+s.status}>{s.status==='review'?'Awaiting review':s.status==='approved'?'Approved':'Changes requested'}</span><h3>{s.title}</h3><p className="hint">Completed {s.completed}</p>{s.url&&<a className="secondary" href={s.url} target="_blank" rel="noopener noreferrer">Open in Drive <ArrowUpRight size={14}/></a>}</div></article>)}</div>:<Empty className="empty"><FolderOpen size={28}/><h3>Your work belongs here</h3><p>Submit completed work against an assigned goal to track it here.</p></Empty>}</section></div>
}
