import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database,syncTaskSheet} from '@/db/raw';
import type {Person} from '@/lib/manager';

export const dynamic='force-dynamic';
type Task={id:string;member_id:string;work_date:string;original_work_date:string|null;title:string;category:string;quantity:number;due_date:string;priority:string;status:string;estimated_hours:number;actual_hours:number;notes:string;started_at:string|null;elapsed_seconds:number;submitted_at:string|null;delete_requested_at:string|null;delete_reason:string;version:number};
class Problem extends Error{constructor(message:string,public statusCode=400){super(message)}}
const reply=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
function field(v:unknown,max:number){if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new Problem('Complete all required fields.');return v.trim()}
function date(v:unknown){const s=field(v,10);if(!/^\d{4}-(0[1-9]|1[0-2])-([0-2]\d|3[01])$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)throw new Problem('Choose a valid date.');return s}
function hours(v:unknown){const n=Number(v);if(!Number.isFinite(n)||n<0||n>1000)throw new Problem('Estimated hours must be between 0 and 1000.');return n}
function quantity(v:unknown,unit:string){const n=Number(v);if(!Number.isFinite(n)||n<=0||n>100000||(unit==='jobs'&&!Number.isInteger(n)))throw new Problem('Enter a positive quantity; jobs must be whole numbers.');return n}
async function context(){const user=await getChatGPTUser();if(!user)throw new Problem('Sign in to your workspace.',401);const db=database();const me=await db.prepare('SELECT * FROM people WHERE user_id=? AND active=1').bind(user.userId).first<Person>();if(!me)throw new Problem('You do not have workspace access.',403);return {db,me}}
function elapsed(task:Task,now:number){return task.elapsed_seconds+(task.started_at?Math.max(0,Math.floor((now-Date.parse(task.started_at))/1000)):0)}
async function carryForward(db:ReturnType<typeof database>,memberId:string,today:string){const tasks=(await db.prepare("SELECT * FROM daily_tasks WHERE member_id=? AND work_date<? AND submitted_at IS NULL AND status IN ('todo','progress','hold') ORDER BY work_date,id").bind(memberId,today).all<Task>()).results;if(!tasks.length)return;const now=Date.now();for(const task of tasks){const endOfDay=Date.parse(`${task.work_date}T12:30:00.000Z`),seconds=task.status==='progress'&&task.started_at?task.elapsed_seconds+Math.max(0,Math.floor((Math.min(now,endOfDay)-Date.parse(task.started_at))/1000)):task.elapsed_seconds;const status=task.status==='progress'?'hold':task.status;await db.prepare("UPDATE daily_tasks SET original_work_date=COALESCE(original_work_date,work_date),work_date=?,due_date=CASE WHEN due_date<? THEN ? ELSE due_date END,status=?,started_at=NULL,elapsed_seconds=?,version=version+1 WHERE id=? AND member_id=? AND version=? AND submitted_at IS NULL").bind(today,today,today,status,seconds,task.id,memberId,task.version).run()}}
async function pauseAtEndOfDay(db:ReturnType<typeof database>,memberId:string,today:string){const cutoff=Date.parse(`${today}T12:30:00.000Z`);if(Date.now()<cutoff)return;const tasks=(await db.prepare("SELECT * FROM daily_tasks WHERE member_id=? AND work_date=? AND status='progress' AND submitted_at IS NULL").bind(memberId,today).all<Task>()).results;for(const task of tasks){const seconds=task.started_at?task.elapsed_seconds+Math.max(0,Math.floor((cutoff-Date.parse(task.started_at))/1000)):task.elapsed_seconds;await db.prepare("UPDATE daily_tasks SET status='hold',started_at=NULL,elapsed_seconds=?,version=version+1 WHERE id=? AND member_id=? AND version=? AND status='progress'").bind(seconds,task.id,memberId,task.version).run()}}
export async function GET(req:Request){try{const {db,me}=await context();const url=new URL(req.url),serverNow=Date.now(),today=new Date(serverNow).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});if(['creator','manager'].includes(me.role)){await carryForward(db,me.id,today);await pauseAtEndOfDay(db,me.id,today)}if(url.searchParams.get('deletions')==='1'){if(!['manager','admin'].includes(me.role))throw new Problem('Only team leads review deletion requests.',403);const rows=(await db.prepare(`SELECT d.* FROM daily_tasks d JOIN people p ON p.id=d.member_id WHERE d.delete_requested_at IS NOT NULL AND d.status!='deleted' AND ${me.role==='admin'?'1=1':'p.manager_id=?'} ORDER BY d.delete_requested_at`).bind(...(me.role==='admin'?[]:[me.id])).all<Task>()).results;return reply({tasks:rows,serverNow,serverToday:today})}if(url.searchParams.get('open')==='1'||url.searchParams.get('ready')==='1'){if(!['creator','manager'].includes(me.role))throw new Problem('Only members can choose tasks to submit.',403);const revisions=url.searchParams.get('ready')==='1';const rows=(await db.prepare(`SELECT d.* FROM daily_tasks d LEFT JOIN submissions s ON s.daily_task_id=d.id WHERE d.member_id=? AND d.submitted_at IS NULL AND d.delete_requested_at IS NULL AND d.status='ready' AND (s.id IS NULL${revisions?" OR s.status='changes'":''}) ORDER BY d.work_date DESC,d.id DESC`).bind(me.id).all<Task>()).results;return reply({tasks:rows,serverNow,serverToday:today})}const day=date(url.searchParams.get('date')||today);const rows=(await db.prepare(`SELECT d.* FROM daily_tasks d JOIN people p ON p.id=d.member_id WHERE d.work_date=? AND ${me.role==='admin'?'1=1':me.role==='manager'?(url.searchParams.get('personal')==='1'?'d.member_id=?':'p.manager_id=?'):'d.member_id=?'} ORDER BY p.name,d.id`).bind(...(me.role==='admin'?[day]:[day,me.id])).all<Task>()).results;return reply({tasks:rows,serverNow,serverToday:today})}catch(e){return error(e)}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)throw new Problem('Origin not allowed.',403);const {db,me}=await context();if(!['creator','manager'].includes(me.role))throw new Problem('Only team members can update their own daily tasks.',403);const raw=await req.text();if(raw.length>10000)throw new Problem('Request too large.');const body=JSON.parse(raw);if(body.action==='sync-sheet')return reply(await syncTaskSheet(me.id));const task=body.id?await db.prepare('SELECT * FROM daily_tasks WHERE id=? AND member_id=?').bind(field(body.id,100),me.id).first<Task>():null;if(body.id&&(!task||task.status==='deleted'))throw new Problem('Task unavailable.',404);if(body.id&&task?.version!==body.version)throw new Problem('Task changed. Refresh and try again.',409);const taskId=task?.id||crypto.randomUUID();
 if(body.action==='pause-eod'){const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});await pauseAtEndOfDay(db,me.id,today);return reply({ok:true})}
 if(body.action==='delete'){if(task!.submitted_at)throw new Problem('Submitted tasks cannot be deleted.');if(await db.prepare('SELECT id FROM submissions WHERE daily_task_id=?').bind(task!.id).first())throw new Problem('This task has a submission waiting for revision. Revise and resubmit it instead of deleting.',409);const reason=field(body.reason,1000);const stamp=new Date().toISOString();const result=await db.prepare("UPDATE daily_tasks SET delete_requested_at=?,delete_reason=?,status=CASE WHEN status='progress' THEN 'hold' ELSE status END,started_at=NULL,elapsed_seconds=?,version=version+1 WHERE id=? AND member_id=? AND version=? AND delete_requested_at IS NULL").bind(stamp,reason,elapsed(task!,Date.now()),task!.id,me.id,body.version).run();if(!result.meta.changes)throw new Problem('A deletion request already exists or the task changed.',409);return reply({ok:true})}
 if(body.action==='cancel-delete'){if(!task)throw new Problem('Task unavailable.',404);const result=await db.prepare("UPDATE daily_tasks SET delete_requested_at=NULL,delete_reason='',version=version+1 WHERE id=? AND member_id=? AND version=? AND delete_requested_at IS NOT NULL").bind(task.id,me.id,body.version).run();if(!result.meta.changes)throw new Problem('This task has no deletion request or it changed.',409);return reply({ok:true})}
 if(task?.delete_requested_at&&['start','complete','save'].includes(body.action))throw new Problem('This task is waiting for deletion approval. Withdraw the request to continue working on it.',409);
 if(body.action==='start'){if(!task||task.submitted_at||task.status==='done')throw new Problem('This task cannot be started.');if(task.status==='progress')return reply({ok:true});const now=Date.now(),stamp=new Date(now).toISOString();const others=(await db.prepare("SELECT * FROM daily_tasks WHERE member_id=? AND status='progress' AND id!=?").bind(me.id,task.id).all<Task>()).results;const changes=others.map(other=>db.prepare("UPDATE daily_tasks SET status='hold',started_at=NULL,elapsed_seconds=?,version=version+1 WHERE id=? AND member_id=? AND version=?").bind(elapsed(other,now),other.id,me.id,other.version));changes.push(db.prepare("UPDATE daily_tasks SET status='progress',started_at=?,version=version+1 WHERE id=? AND member_id=? AND version=?").bind(stamp,task.id,me.id,task.version));const result=await db.batch(changes);if(result.some(r=>!r.meta.changes))throw new Problem('Task changed. Refresh and try again.',409);return reply({ok:true})}
 if(body.action==='pause'){if(!task||task.status!=='progress'||!task.started_at)throw new Problem('Only active work can be paused.');const result=await db.prepare("UPDATE daily_tasks SET status='hold',started_at=NULL,elapsed_seconds=?,version=version+1 WHERE id=? AND member_id=? AND version=?").bind(elapsed(task,Date.now()),task.id,me.id,task.version).run();if(!result.meta.changes)throw new Problem('Task changed. Refresh and try again.',409);return reply({ok:true})}
 if(body.action==='complete'){if(!task||task.submitted_at||!['progress','hold'].includes(task.status)||(!task.started_at&&task.elapsed_seconds<=0))throw new Problem('Start this task before marking it complete.');const seconds=elapsed(task,Date.now()),actual=Math.round(seconds/36)/100;const result=await db.prepare("UPDATE daily_tasks SET status='ready',started_at=NULL,elapsed_seconds=?,actual_hours=?,version=version+1 WHERE id=? AND member_id=? AND version=?").bind(seconds,actual,task.id,me.id,task.version).run();if(!result.meta.changes)throw new Problem('Task changed. Refresh and try again.',409);return reply({ok:true})}
 if(body.action!=='save')throw new Problem('Unknown action.');if(task?.submitted_at)throw new Problem('This task has already been submitted.');const workDate=date(body.work_date),today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});if(workDate<today&&(!task||workDate!==task.work_date))throw new Problem('New tasks cannot be added for a past date.');const dueDate=date(body.due_date),title=field(body.title,160),category=field(body.category,60),notes=typeof body.notes==='string'&&body.notes.length<=2000?body.notes.trim():(()=>{throw new Problem('Notes are too long.')})();const assignedGoal=await db.prepare('SELECT t.unit FROM plans p JOIN goal_types t ON t.id=p.type_id WHERE p.member_id=? AND p.month=? AND t.name=?').bind(me.id,workDate.slice(0,7),category).first<{unit:string}>();if(!assignedGoal&&!(task?.category===category&&task.work_date===workDate))throw new Problem('Choose a goal assigned to you for the work month.');if(!['low','normal','high'].includes(body.priority))throw new Problem('Choose a valid priority.');const estimated=hours(body.estimated_hours),amount=quantity(body.quantity??1,assignedGoal?.unit||'jobs');if(task){const result=await db.prepare('UPDATE daily_tasks SET work_date=?,title=?,category=?,quantity=?,due_date=?,priority=?,estimated_hours=?,notes=?,version=version+1 WHERE id=? AND member_id=? AND version=?').bind(workDate,title,category,amount,dueDate,body.priority,estimated,notes,task.id,me.id,body.version).run();if(!result.meta.changes)throw new Problem('Task changed. Refresh and try again.',409)}else await db.prepare('INSERT INTO daily_tasks(id,member_id,work_date,title,category,quantity,due_date,priority,status,estimated_hours,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(taskId,me.id,workDate,title,category,amount,dueDate,body.priority,'todo',estimated,notes).run();return reply({ok:true})
}catch(e){return error(e)}}
function error(e:unknown){if(e instanceof Problem)return reply({error:e.message},e.statusCode);if(e instanceof SyntaxError||e instanceof RangeError)return reply({error:'Check the submitted task details.'},400);console.error(e);return reply({error:'Could not load or save daily tasks.'},503)}
