import {sqliteTable,text,integer,real,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const workspace=sqliteTable('workspace',{id:integer('id').primaryKey(),ownerId:text('owner_id').notNull()});
export const personalGoals=sqliteTable('personal_goals',{id:text('id').primaryKey(),memberId:text('member_id').notNull(),month:text('month').notNull(),kind:text('kind').notNull(),quantity:real('quantity').notNull(),hoursPerJob:real('hours_per_job')},t=>[uniqueIndex('personal_goal_member_month_kind').on(t.memberId,t.month,t.kind)]);
export const members=sqliteTable('members',{id:text('id').primaryKey(),userId:text('user_id'),email:text('email').notNull().unique(),name:text('name').notNull(),role:text('role').notNull()});
export const channels=sqliteTable('channels',{id:text('id').primaryKey(),name:text('name').notNull().unique(),folder:text('folder').notNull().default('')});
export const targets=sqliteTable('targets',{id:text('id').primaryKey(),channelId:text('channel_id').notNull(),month:text('month').notNull(),kind:text('kind').notNull(),quantity:integer('quantity').notNull()},t=>[uniqueIndex('target_month_channel_kind').on(t.month,t.channelId,t.kind)]);
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),title:text('title').notNull(),channelId:text('channel_id').notNull(),kind:text('kind').notNull(),due:text('due').notNull(),assignee:text('assignee').notNull(),status:text('status').notNull().default('planned'),driveUrl:text('drive_url').notNull().default(''),completed:text('completed').notNull().default(''),notes:text('notes').notNull().default(''),feedback:text('feedback').notNull().default(''),scheduled:text('scheduled').notNull().default(''),completedHours:real('completed_hours').notNull().default(0),version:integer('version').notNull().default(1)});

// Fresh manager workspace. Original tracker tables remain available for recovery.
export const people=sqliteTable('people',{id:text('id').primaryKey(),userId:text('user_id'),employeeId:text('employee_id'),email:text('email').notNull().unique(),name:text('name').notNull(),role:text('role').notNull(),job:text('job').notNull(),managerId:text('manager_id'),active:integer('active').notNull().default(1)});
export const goalTypes=sqliteTable('goal_types',{id:text('id').primaryKey(),managerId:text('manager_id').notNull(),name:text('name').notNull(),unit:text('unit').notNull()},t=>[uniqueIndex('goal_type_manager_name').on(t.managerId,t.name)]);
export const plans=sqliteTable('plans',{id:text('id').primaryKey(),memberId:text('member_id').notNull(),typeId:text('type_id').notNull(),month:text('month').notNull(),target:real('target').notNull(),hoursPerJob:real('hours_per_job')},t=>[uniqueIndex('plan_member_month_type').on(t.memberId,t.month,t.typeId)]);
export const submissions=sqliteTable('submissions',{id:text('id').primaryKey(),planId:text('plan_id').notNull(),dailyTaskId:text('daily_task_id'),title:text('title').notNull(),url:text('url').notNull(),completed:text('completed').notNull(),quantity:real('quantity').notNull(),status:text('status').notNull().default('review'),feedback:text('feedback').notNull().default(''),version:integer('version').notNull().default(1)},t=>[uniqueIndex('submission_daily_task').on(t.dailyTaskId)]);
export const dailyTasks=sqliteTable('daily_tasks',{id:text('id').primaryKey(),memberId:text('member_id').notNull(),workDate:text('work_date').notNull(),originalWorkDate:text('original_work_date'),title:text('title').notNull(),category:text('category').notNull(),quantity:real('quantity').notNull().default(1),dueDate:text('due_date').notNull(),priority:text('priority').notNull().default('normal'),status:text('status').notNull().default('todo'),estimatedHours:real('estimated_hours').notNull().default(0),actualHours:real('actual_hours').notNull().default(0),notes:text('notes').notNull().default(''),startedAt:text('started_at'),elapsedSeconds:integer('elapsed_seconds').notNull().default(0),submittedAt:text('submitted_at'),deleteRequestedAt:text('delete_requested_at'),deleteReason:text('delete_reason').notNull().default(''),version:integer('version').notNull().default(1)});
