import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/db/raw';
import {kinds,roles,type Member,type Task} from '@/lib/model';
export const dynamic='force-dynamic';
class Problem extends Error{constructor(message:string,public status=400){super(message)}}
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function current(){const user=await getChatGPTUser();if(!user)throw new Problem('Sign in to open your workspace.',401);const db=database();const email=user.email.trim().toLowerCase();
// First setup happens behind the private Site owner gate. The immutable owner cannot be demoted.
await db.prepare('INSERT OR IGNORE INTO workspace(id,owner_id) VALUES(1,?)').bind(user.userId).run();
const workspace=await db.prepare('SELECT owner_id FROM workspace WHERE id=1').first<{owner_id:string}>();
if(workspace?.owner_id===user.userId)await db.prepare('INSERT OR IGNORE INTO members(id,user_id,email,name,role) VALUES(?,?,?,?,?)').bind(user.userId,user.userId,email,user.fullName||email.split('@')[0],'admin').run();
await db.prepare('UPDATE members SET user_id=? WHERE email=? AND user_id IS NULL').bind(user.userId,email).run();
const me=await db.prepare('SELECT * FROM members WHERE user_id=?').bind(user.userId).first<Member>();if(!me)throw new Problem('Your account is not on this team. Ask the admin to add your sign-in email.',403);return {db,me,owner:workspace!.owner_id}}
function permit(me:Member,allowed:string[]){if(!allowed.includes(me.role))throw new Problem('Your role cannot perform this action.',403)}
function str(x:unknown,max=200,optional=false){if(typeof x!=='string'||(!optional&&!x.trim())||x.length>max)throw new Problem('Check the required fields and text length.');return x.trim()}
function date(x:unknown){const d=str(x,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||Number.isNaN(Date.parse(d+'T00:00:00Z'))||new Date(d+'T00:00:00Z').toISOString().slice(0,10)!==d)throw new Problem('Enter a valid date.');return d}
function drive(x:unknown,optional=false){const s=str(x,2000,optional);if(!s&&optional)return '';let u:URL;try{u=new URL(s)}catch{throw new Problem('Paste a valid Google Drive link.')}if(u.protocol!=='https:'||!['drive.google.com','docs.google.com'].includes(u.hostname)||u.username||u.password)throw new Problem('Use an HTTPS Google Drive or Google Docs link.');return u.href}
async function snapshot(){const {db,me}=await current();const [channels,members,tasks,targets]=await Promise.all([db.prepare('SELECT * FROM channels ORDER BY name').all(),db.prepare('SELECT * FROM members ORDER BY name').all(),me.role==='creator'?db.prepare('SELECT * FROM tasks WHERE assignee=? ORDER BY due DESC').bind(me.id).all():me.role==='scheduler'?db.prepare("SELECT * FROM tasks WHERE status IN ('approved','scheduled') ORDER BY due DESC").all():db.prepare('SELECT * FROM tasks ORDER BY due DESC').all(),db.prepare('SELECT * FROM targets ORDER BY month').all()]);return {me,channels:channels.results,members:members.results.map((m:any)=>me.role==='admin'?m:{id:m.id,name:m.name,role:m.role}),tasks:tasks.results,targets:targets.results}}
function failure(e:unknown){if(e instanceof Problem)return response({error:e.message},e.status);console.error('Workspace operation failed',e);return response({error:'Could not save or load the workspace. Please retry; your form has been kept.'},503)}
export async function GET(){try{return response(await snapshot())}catch(e){return failure(e)}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new Problem('Request origin is not allowed.',403);if(Number(request.headers.get('content-length')||0)>30000)throw new Problem('Request is too large.');const {db,me,owner}=await current();const b=await request.json() as Record<string,unknown>;const action=str(b.action);const id=crypto.randomUUID();
if(action==='channel'){permit(me,['admin']);const name=str(b.name,80),folder=drive(b.folder??'',true);try{if(b.id)await db.prepare('UPDATE channels SET name=?,folder=? WHERE id=?').bind(name,folder,str(b.id)).run();else await db.prepare('INSERT INTO channels(id,name,folder) VALUES(?,?,?)').bind(id,name,folder).run()}catch{throw new Problem('A channel with this name already exists.')}}
else if(action==='target'){permit(me,['admin']);const channel=str(b.channel_id),month=str(b.month,7),kind=str(b.kind);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||!Object.hasOwn(kinds,kind)||!Number.isInteger(b.quantity)||Number(b.quantity)<0||Number(b.quantity)>100000)throw new Problem('Enter a valid month, type and target quantity.');if(!await db.prepare('SELECT id FROM channels WHERE id=?').bind(channel).first())throw new Problem('Channel not found.');await db.prepare('INSERT INTO targets(id,channel_id,month,kind,quantity) VALUES(?,?,?,?,?) ON CONFLICT(month,channel_id,kind) DO UPDATE SET quantity=excluded.quantity').bind(id,channel,month,kind,b.quantity).run()}
else if(action==='member'){permit(me,['admin']);const email=str(b.email,254).toLowerCase(),name=str(b.name,100),role=str(b.role);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!Object.hasOwn(roles,role))throw new Problem('Enter a valid email and role.');const existing=await db.prepare('SELECT * FROM members WHERE email=?').bind(email).first<Member>();if(existing?.user_id===owner&&role!=='admin')throw new Problem('The workspace owner must remain an admin.');await db.prepare('INSERT INTO members(id,email,name,role) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role').bind(id,email,name,role).run()}
else if(action==='remove_member'){permit(me,['admin']);const member=await db.prepare('SELECT * FROM members WHERE id=?').bind(str(b.id)).first<Member>();if(!member)throw new Problem('Member not found.',404);if(member.user_id===owner||member.id===me.id)throw new Problem('You cannot remove yourself or the workspace owner.');if(await db.prepare('SELECT id FROM tasks WHERE assignee=? LIMIT 1').bind(member.id).first())throw new Problem('Reassign this member’s tasks before removing them.');await db.prepare('DELETE FROM members WHERE id=?').bind(member.id).run()}
else if(action==='task'){permit(me,['admin','manager','creator']);const title=str(b.title,160),channel=str(b.channel_id),kind=str(b.kind),due=date(b.due),assignee=me.role==='creator'?me.id:str(b.assignee),notes=str(b.notes??'',3000,true);if(!Object.hasOwn(kinds,kind))throw new Problem('Choose a work type.');if(!await db.prepare('SELECT id FROM channels WHERE id=?').bind(channel).first())throw new Problem('Choose an existing channel.');if(!await db.prepare("SELECT id FROM members WHERE id=? AND role!='scheduler'").bind(assignee).first())throw new Problem('Choose a creator, manager or admin.');if(b.id){const old=await db.prepare('SELECT * FROM tasks WHERE id=?').bind(str(b.id)).first<Task>();if(!old)throw new Problem('Task not found.',404);if(old.completed&&old.kind!==kind)throw new Problem('The goal type cannot change after submission. Create a new task for a different goal.');if(me.role==='creator'&&old.assignee!==me.id)throw new Problem('Only your own tasks can be edited.',403);if(['approved','scheduled'].includes(old.status))throw new Problem('Approved tasks cannot be edited.');const r=await db.prepare('UPDATE tasks SET title=?,channel_id=?,kind=?,due=?,assignee=?,notes=?,version=version+1 WHERE id=? AND version=?').bind(title,channel,kind,due,assignee,notes,old.id,b.version).run();if(!r.meta.changes)throw new Problem('This task changed. Close it and refresh before editing.',409)}else await db.prepare('INSERT INTO tasks(id,title,channel_id,kind,due,assignee,notes) VALUES(?,?,?,?,?,?,?)').bind(id,title,channel,kind,due,assignee,notes).run()}
else if(['submit','start','approve','changes','schedule'].includes(action)){const old=await db.prepare('SELECT * FROM tasks WHERE id=?').bind(str(b.id)).first<Task>();if(!old)throw new Problem('Task not found.',404);let status=old.status,url=old.drive_url,completed=old.completed,feedback=old.feedback,scheduled=old.scheduled,hours=old.completed_hours;
if(action==='submit'||action==='start'){permit(me,['admin','manager','creator']);if(me.role==='creator'&&old.assignee!==me.id)throw new Problem('You can only update your own tasks.',403);if(!['planned','progress','changes','review'].includes(old.status))throw new Problem('This task has already been approved.');if(action==='start'){if(!['planned','changes'].includes(old.status))throw new Problem('This task is already started.');status='progress'}else{url=drive(b.drive_url,old.kind==='ai_hours');if(old.kind==='ai_hours'){hours=Number(b.completed_hours);if(!Number.isFinite(hours)||hours<=0||hours>744)throw new Problem('Enter completed AI hours between 0 and 744.');}completed=date(b.completed);if(completed>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}))throw new Problem('Completion cannot be in the future.');status='review';feedback=''}}
if(action==='approve'||action==='changes'){permit(me,['admin','manager']);if(old.status!=='review')throw new Problem('Only submitted work can be reviewed.');status=action==='approve'?'approved':'changes';feedback=action==='changes'?str(b.feedback,2000):''}
if(action==='schedule'){permit(me,['admin','manager','scheduler']);if(old.status!=='approved')throw new Problem('Only approved work can be scheduled.');scheduled=date(b.scheduled);status='scheduled'}
const r=await db.prepare('UPDATE tasks SET status=?,drive_url=?,completed=?,feedback=?,scheduled=?,completed_hours=?,version=version+1 WHERE id=? AND version=?').bind(status,url,completed,feedback,scheduled,hours,old.id,b.version).run();if(!r.meta.changes)throw new Problem('This task changed. Close it and refresh before updating.',409)}else throw new Problem('Unknown action.');return response(await snapshot())}catch(e){return failure(e)}}

